### ISSUE TITLE
Problems tokenizing Norwegian/Danish characters

### ISSUE THREAD

**Issue by peregilk** [google-research/ALBERT#113]
I am training a Norwegian version AlBert and had problems tokenizing some special characters.

The Norwegian/Danish alphabet has three additional letters: æ, ø, å. The last letter "å" seem to be encoded as a common "a". It is a bit strange since the same library seem to be able to build dictionaries with words containing "å".

The following Colab-code (https://colab.research.google.com/drive/16VU4IBLrKPk54JjNW-KgpyNOVDdZhOKl) shows that the words "så" and "sa" is given the same id, even when both words exists in the vocabulary. The vocab-file used is from multilingual Bert. Tokenization in Bert has the same behaviour.

**Comment by mollerhoj** [comment]
The bert tokenizer converts "å" and "ä" into a, and ö into "o". This happens in an attempt to remove accents from characters.

It's seems rather wasteful to tokenize the input , because the characters are still in the vocabulary, meaning that "så" and "sa" both takes up vocab space, but without any added value.

The issue comes from this function in the bert tokenizer: https://github.com/google-research/ALBERT/blob/master/tokenization.py#L333, which converts the text into "normalized form" (meaning that "å" is split into "a" and " ̊") and then removes the " ̊".

**Comment by peregilk** [comment]
Thanks. I think I was able to solve the issue. Normalising the accented characters are tied to "do_lower_case=True" in FullTokenizer. Setting this parameter does no longer convert "så" to "sa".
