### ISSUE TITLE
"no dropout" on v2 models

### ISSUE THREAD

**Issue by peregilk** [google-research/ALBERT#23]
You say that you are using "no dropout" on the TFHub v2-models. However, looking at the albert_config.json-files there seem to be dropout on most models (https://tfhub.dev/google/albert_base/2). Only on the xxlarge, there is no dropout (https://tfhub.dev/google/albert_xxlarge/2). What is correct?

**Comment by lanzhzh** [comment]
fixed. Thanks!

**Comment by matteodelv** [comment]
To which extent has this been fixed?
I guess there is some confusion regarding dropout and the various model versions released.
According to the paper, and the Table 15 in particular, ALBERT Dropout rate and Classifier Dropout rate are specified. What is their relation with attention_probs_dropout_prob and hidden_dropout_prob parameters?

Furthermore, looking at ALBERT xxlarge configs on TF-Hub, both v1 and v2 have dropout rate to 0. Is this wrong as the v1 has a 0.1 dropout rate?
Why the other v2 configs (base, large and xlarge) still have the attention_probs_dropout_prob to 0.1 instead of 0, as for the xxlarge config?

**Comment by Danny-Google** [comment]
We fix the configuration on albert-v2, as can be seen here (https://tfhub.dev/google/albert_base/2). 
For v1, we had dropout of ALBERT-xxlarge to be 0 and others to be 0.1. For albert-v2, we further remove dropout in all settings.

**Comment by matteodelv** [comment]
Thank you for the fix!
So, is it correct to assume attention_probs_dropout_prob == Classifier DR (on Table 15), while hidden_dropout_prob == ALBERT DR?

**Comment by Danny-Google** [comment]
Both attention_probs_dropout_prob and hidden_dropout_prob are ALBERT DR. If you use v2, they all set to 0. Classifier DR is this thing (https://github.com/google-research/ALBERT/blob/master/classifier_utils.py#L829), we always set it to 0.1

**Comment by matteodelv** [comment]
So, is `attention_probs_dropout_prob` explicitly set to 0 in the code for v2 model?
I'm asking because v2 configurations ([base](https://tfhub.dev/google/albert_base/2), [large](https://tfhub.dev/google/albert_large/2) and [xlarge](https://tfhub.dev/google/albert_xlarge/2)) on TF-Hub still have `attention_probs_dropout_prob` = 0.1 in the json.

**Comment by Danny-Google** [comment]
Good catch, let me fix them.

**Comment by matteodelv** [comment]
Awesome! Now everything is less confused, thanks!
